---
title: Rationale
timezone: UTC
collections:
  articles:
    title: Articles
    output: true
  our-work:
    title: Our work
    output: true
    description: Your design experts for visual identities, digital, and publications.
  posts:
    title: Posts
    output: true
  resources:
    title: Resources
    output: true
  shop:
    title: Shop
    output: true
  uploads:
    title: Uploads
    output: true
  image-ratios:
    title: image_ratios
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: default
- scope:
    path: ''
    type: our-work
  values:
    layout: project
    excerpt_text: 
    year: 
    images:
    - image: 
      alt: 
      image_ratio: 
      color: 
    thumb_image:
      image: 
      alt: 
      image_ratio: 
      color: 
    is_featured: 
    og_image: 
- scope:
    path: ''
    type: resources
  values:
    layout: resource
    author: 
    imgcount: 
    images:
    - image: 
      alt: 
      image_ratio: 
      color: 
    thumb_image:
      image: 
      alt: 
      image_ratio: 
      color: 
    download_file: 
    og_image: 
- scope:
    path: ''
    type: shop
  values:
    layout: product-detail
    price: 
    buylink: 
    buytag: 
    is_buyactive: 
    imgcount: 
    images:
    - image: 
      alt: 
      image_ratio: 
      color: 
    thumb_image:
      image: 
      alt: 
      image_ratio: 
      color: 
    og_image: 
- scope:
    path: ''
    type: articles
  values:
    layout: article
    featured_text: 
    excerpt_text: 
    featured_image:
      image: 
      alt: 
      image_ratio: 
      color: 
    detail_images:
    - image: 
      alt: 
      image_ratio: 
      color: 
    og_image: 
url: https://rationale-design.com
permalink: pretty
exclude:
- README.md
- node_modules
- package.json
- gulpfile.js
gems:
- jekyll-sitemap
- jekyll-feed
description: Rationale is a graphic design studio north of Seattle in Everett, Washington,
  providing world-class expertise in visual identity design, websites, applications,
  publications and more.
og_image: "/uploads/rationale_og.jpg"
